<?php
function general_init() {}
//---------------------------------
function general_hook_info () {
    return array('general' => array('info' => t('Mathe-Nachhilfe general Module.')));
}
function general_permission () {
    return array('view general page' => array('title' => t('Acces general page')));
}
function general_node_access($op, $node, $account) {
  switch ($op) {
    case 'view':
      if (user_access('view general page', $account))
        return NODE_ACCESS_ALLOW;
    break;
    default:
      return NODE_ACCESS_IGNORE;
    break;
  }
}
//----------------------------------------------------------------------------
//----------------------------------------------------------------------------
function general_block_info () {
  $blocks['sitemap'] = array(
    'info' => t('(block footer) Site map'),
    'cache' => DRUPAL_NO_CACHE
  );
  return $blocks;
}
function general_block_view ($delta = '') {
  switch ($delta) {
    case 'sitemap':
      $block = array(
        #'subject' => t('Site map'),
        #'content' => drupal_get_form('sitemap_menu_block'),
      );
    break;
    default:
        $block = null;
    break;
  }
  return $block;
}
//----------------------------------------------------------------------------
function sitemap_menu_block ($form, &$form_state) {  
  $form['map'] = array(
    '#type' => 'container',
    '#markup' => 'Calendar',
    '#prefix' => '<table class="sitemap-table">',
    '#suffix' => '</table>'
  );
  $form['map']['calendar'] = array(
    '#type' => 'markup',
    '#markup' => 'Calendar',
    '#prefix' => '<tr><td><a href="/calendar">',
    '#suffix' => '</a></td></tr>'
  );
  $form['map']['employees'] = array(
    '#type' => 'markup',
    '#markup' => 'Employees',
    '#prefix' => '<tr><td><a href="/employees">',
    '#suffix' => '</a></td></tr>'
  );
  $form['map']['employees-create'] = array(
    '#type' => 'markup',
    '#markup' => ' - Add entry',
    '#prefix' => '<tr><td><a href="/employees/create">',
    '#suffix' => '</a></td></tr>'
  );
  $form['map']['lesson-hour'] = array(
    '#type' => 'markup',
    '#markup' => 'Lesson hour',
    '#prefix' => '<tr><td><a href="/hour">',
    '#suffix' => '</a></td></tr>'
  );
  $form['map']['students'] = array(
    '#type' => 'markup',
    '#markup' => 'Students',
    '#prefix' => '<tr><td><a href="/students">',
    '#suffix' => '</a></td></tr>'
  );
  $form['map']['students-create'] = array(
    '#type' => 'markup',
    '#markup' => ' - Add entry',
    '#prefix' => '<tr><td><a href="/students/create">',
    '#suffix' => '</a></td></tr>'
  );
  $form['map']['Search'] = array(
    '#type' => 'markup',
    '#markup' => 'Search',
    '#prefix' => '<tr><td><a href="/search">',
    '#suffix' => '</a></td></tr>'
  );
  return $form;
}
//----------------------------------------------------------------------------
function general_redirect_403($form, &$form_states) {
  #drupal_goto('user/login');

  return drupal_set_message("Access Denied: Please Login");
  global $user;
  if ($user->uid) { // this user is already logged in
    print "Access Denied: You do not have access to this page.";
  } else {
    drupal_set_message("Access Denied: Please Login");
    $dest = drupal_get_destination();
    drupal_goto('user/login', $dest);
  }
}
function general_redirect_404($form, &$form_states) {
  #drupal_goto('user/login');

  return drupal_set_message("Access Denied: Please Login");
  return TRUE;
}
//----------------------------------------------------------------------------
 function general_menu() {
  $items['acces-denied'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => 'general_redirect_403',
    'type' => MENU_CALLBACK,
  );
  $items['not-found'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => 'general_redirect_403',
    'type' => MENU_CALLBACK,
  );
  return $items;
}
